f2fs: fix build error caused by bad backport Bad backport: https://github.com/GlassROM-devices/android_kernel_oneplus_msm8994/commit/ed2579c610676cdd7f412923a4315586beaa4aaa Upstream commit: https://lore.kernel.org/patchwork/patch/874330/ Journalled quotas were never backported to our 3.10 kernel so this is unsupported
$ make fs/f2fs/ -j4
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CALL    scripts/checksyscalls.sh
<stdin>:1226:2: warning: #warning syscall sched_setattr not implemented
[-Wcpp]
<stdin>:1229:2: warning: #warning syscall sched_getattr not implemented
[-Wcpp]
cc1: warning: unrecognized command line option
'-Wno-multistatement-macros'
  CC      fs/f2fs/dir.o
  CC      fs/f2fs/file.o
  CC      fs/f2fs/inode.o
  CC      fs/f2fs/namei.o
  CC      fs/f2fs/hash.o
  CC      fs/f2fs/super.o
  CC      fs/f2fs/inline.o
  CC      fs/f2fs/checkpoint.o
fs/f2fs/super.c: In function 'f2fs_fill_super':
fs/f2fs/super.c:2270:18: error: 'F2FS_MAXQUOTAS' undeclared (first use
in this function); did you mean 'XQM_MAXQUOTAS'?
  for (i = 0; i < F2FS_MAXQUOTAS; i++)
                  ^~~~~~~~~~~~~~
                  XQM_MAXQUOTAS
fs/f2fs/super.c:2270:18: note: each undeclared identifier is reported
only once for each function it appears in
fs/f2fs/super.c:2271:12: error: 'struct f2fs_sb_info' has no member
named 's_qf_names'
   kfree(sbi->s_qf_names[i]);
            ^~
fs/f2fs/super.c: At top level:
cc1: warning: unrecognized command line option
'-Wno-multistatement-macros'
make[1]: *** [scripts/Makefile.build:308: fs/f2fs/super.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1461: fs/f2fs/] Error 2

Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>